cvrminer/app/__init__.py
"""cvrminer app."""


from __future__ import absolute_import, division, print_function

from flask import Flask
from flask_bootstrap import Bootstrap, StaticCDN


def create_app(smiley=False):
    """Create app.

    Factory for app.

    Parameters
    ----------
    smiley : bool, optional
        Determines whether the smiley functionality should be setup.

    """
    app = Flask(__name__)
    Bootstrap(app)

    # Serve assets from wmflabs for privacy reasons
    app.extensions['bootstrap']['cdns']['jquery'] = StaticCDN()
    app.extensions['bootstrap']['cdns']['bootstrap'] = StaticCDN()

    if smiley:
        from ..smiley import Smiley

        app.smiley = Smiley()
    else:
        app.smiley = None

    from .views import main as main_blueprint
    app.register_blueprint(main_blueprint)

    return app

cvrminer/app/views.py
"""Views for cvrminer app."""

from flask import (Blueprint, current_app, redirect, render_template, url_for)

from werkzeug.routing import BaseConverter

from ..xbrler import search_for_regnskaber
from ..wikidata import cvr_to_q


class RegexConverter(BaseConverter):
    """Converter for regular expression routes.

    References
    ----------
    https://stackoverflow.com/questions/5870188

    """

    def __init__(self, url_map, *items):
        """Set up regular expression matcher."""
        super(RegexConverter, self).__init__(url_map)
        self.regex = items[0]


def add_app_url_map_converter(self, func, name=None):
    """Register a custom URL map converters, available application wide.

    References
    ----------
    https://coderwall.com/p/gnafxa/adding-custom-url-map-converters-to-flask-blueprint-objects

    """
    def register_converter(state):
        state.app.url_map.converters[name or func.__name__] = func

    self.record_once(register_converter)


Blueprint.add_app_url_map_converter = add_app_url_map_converter
main = Blueprint('app', __name__)
main.add_app_url_map_converter(RegexConverter, 'regex')


# Wikidata item identifier matcher
q_pattern = r'<regex("Q[1-9]\d*"):q>'


@main.route("/")
def index():
    """Return index page of for app."""
    return render_template('index.html')


@main.route("/" + q_pattern)
def redirect_q(q):
    """Detect and redirect to CVRminer class page.

    Parameters
    ----------
    q : str
        Wikidata item identifier

    """
    class_ = 'company'
    method = 'app.show_' + class_
    return redirect(url_for(method, q=q), code=302)


@main.route("/smiley/")
def smiley():
    """Return smiley page of for app."""
    if current_app.smiley:
        table = current_app.smiley.db.tables.smiley.head(n=10000).to_html()
    else:
        table = ''
    return render_template('smiley.html', table=table)


@main.route("/cvr/<int:cvr>")
def show_cvr(cvr):
    """Return CVR page of for app."""
    q = cvr_to_q(cvr)
    regnskaber = search_for_regnskaber(cvr=cvr)
    return render_template('cvr.html',
                           cvr=cvr, regnskaber=regnskaber, q=q)


@main.route('/branch/' + q_pattern)
def show_branche(q):
    """Return HTML rendering for specific branch.

    Parameters
    ----------
    q : str
        Wikidata item identifier.

    Returns
    -------
    html : str
        Rendered HTML.

    """
    return render_template('branch.html', q=q)


@main.route('/branch/')
def show_branch_empty():
    """Return rendered index page for branch.

    Returns
    -------
    html : str
        Rendered HTML page for branch index page.

    """
    return render_template('branch_empty.html')


@main.route('/company/')
def show_company_empty():
    """Return rendered index page for company.

    Returns
    -------
    html : str
        Rendered HTML page for branch index page.

    """
    return render_template('company_empty.html')


@main.route('/company/' + q_pattern)
def show_company(q):
    """Return HTML rendering for specific company.

    Parameters
    ----------
    q : str
        Wikidata item identifier.

    Returns
    -------
    html : str
        Rendered HTML.

    """
    return render_template('company.html', q=q)


@main.route('/exchange/')
def show_exchange_empty():
    """Return rendered index page for branch.

    Returns
    -------
    html : str
        Rendered HTML page for branch index page.

    """
    return render_template('exchange_empty.html')


@main.route('/exchange/' + q_pattern)
def show_exchange(q):
    """Return HTML rendering for specific exchange.

    Parameters
    ----------
    q : str
        Wikidata item identifier.

    Returns
    -------
    html : str
        Rendered HTML.

    """
    return render_template('exchange.html', q=q)


@main.route('/person/')
def show_person_empty():
    """Return rendered index page for person.

    Returns
    -------
    html : str
        Rendered HTML page for branch index page.

    """
    return render_template('person_empty.html')


@main.route('/person/' + q_pattern)
def show_person(q):
    """Return HTML rendering for specific person.

    Parameters
    ----------
    q : str
        Wikidata item identifier.

    Returns
    -------
    html : str
        Rendered HTML.

    """
    return render_template('person.html', q=q)

cvrminer/app/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}cvrminer{% endblock %}

{% block head %}
{{super()}}

<link rel="stylesheet" type="text/css" href="/static/jquery.dataTables.min.css">
<link rel="stylesheet" type="text/css" href="/cvrminer/static/jquery.dataTables.min.css">

{% endblock %}



{% block scripts %}
{{super()}}

<script type="text/javascript" src="/static/jquery-3.2.1.min.js"></script>
<script type="text/javascript" src="/cvrminer/static/jquery-3.2.1.min.js"></script>

<script src="/static/jquery.dataTables.min.js"></script>
<script src="/cvrminer/static/jquery.dataTables.min.js"></script>

<script type="text/javascript" src="/static/cvrminer.js"></script>
<script type="text/javascript" src="/cvrminer/static/cvrminer.js"></script>


<script type="text/javascript" charset="utf8">
$(document).ready( function () {
    $('.dataframe').DataTable();
} );
</script>

{% endblock %}

{% block navbar %}
<div class="navbar navbar-static-top">
  <ul class="nav nav-pills">
    <li role="presentation"><a href="/">cvrminer</a></li>
    <li role="presentation"><a href="{{ url_for('app.show_person_empty') }}">Person</a></li>
    <li role="presentation"><a href="{{ url_for('app.show_company_empty') }}">Company</a></li>
    <li role="presentation"><a href="{{ url_for('app.show_branch_empty') }}">Branch</a></li>
    <li role="presentation"><a href="{{ url_for('app.show_exchange_empty') }}">Exchange</a></li>
  </ul>
</div>
{% endblock %}

{% block content %}
  <div class="container">
    {% block page_content %}{% endblock %}
  </div>

  <div class="container">
    <hr>
     Data from <a href="https://www.wikidata.org">Wikidata</a>,
    <a href="https://en.wikipedia.org">English Wikipedia</a> and
    <a href="https://erhvervsstyrelsen.dk/">Erhvervsstyrelsen</a>
    |
    Code from 
    <a href="https://github.com/fnielsen/cvrminer">GitHub repository</a>.
  </div>
{% endblock %}

cvrminer/app/templates/branch.html
{% extends "branch_base.html" %}


{% block scripts %}
{{super()}}

<script type="text/javascript">
  listOfCompaniesSparql = `
SELECT ?company ?companyLabel ?country ?countryLabel
WITH {
  SELECT ?company ?country WHERE {
    ?company wdt:P452/wdt:P279* wd:{{ q }} .
    OPTIONAL { ?company wdt:P17 ?country . }
  }
} AS %result
WHERE {
  INCLUDE %result
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en,da,de,fr,jp,nl,no,pl,ru,sv,zh". }
}
ORDER BY ?companyLabel
 `

 
 $(document).ready(function() {
   console.log('In ready')
   sparqlToDataTable(listOfCompaniesSparql, "#list-of-companies");
   console.log('Back from function');
  });
</script>

{% endblock %}




{% block page_content %}


<h1 id="h1">Branch</h1>


<h2>Companies within the branch</h2>

<table class="table table-hover" id="list-of-companies"></table>



{% endblock %}

cvrminer/app/templates/branch_base.html
{% extends "base.html" %}


{% block navbar %}
<div class="navbar navbar-static-top">
  <ul class="nav nav-pills">
    <li role="presentation"><a href="..">cvrminer</a></li>
    <li role="presentation"><a href="../company/">Company</a></li>
    <li role="presentation" class="active"><a href="./">Branch</a></li>
    <li role="presentation"><a href="../exchange/">Exchange</a></li>
  </ul>
</div>
{% endblock %}

cvrminer/app/templates/branch_empty.html
{% extends "branch_base.html" %}

{% block page_content %}


<h1>Branch</h1>

<h2>Examples</h2>

<ul>
  <li><a href="Q190117">Automotive industry</a>
  <li><a href="Q507443">Pharmaceutical industry</a>
</ul>


{% endblock %}

cvrminer/app/templates/company_base.html
{% extends "base.html" %}


{% block navbar %}
<div class="navbar navbar-static-top">
  <ul class="nav nav-pills">
    <li role="presentation"><a href="..">cvrminer</a></li>
    <li role="presentation" class="active"><a href="./">Company</a></li>
    <li role="presentation""><a href="../branch">Branch</a></li>
    <li role="presentation"><a href="../exchange/">Exchange</a></li>
  </ul>
</div>
{% endblock %}

cvrminer/app/templates/company_empty.html
{% extends "company_base.html" %}

{% block page_content %}


<h1>Branch</h1>

<h2>Examples</h2>

<ul>
    <li><a href="Q3949497">KMD A/S</a></li>
    <li><a href="Q27920050">William Demant Invest</a></li>
</ul>


{% endblock %}

cvrminer/app/templates/cvr_base.html
{% extends "base.html" %}

{% block navbar %}
<div class="navbar navbar-static-top">
  <ul class="nav nav-pills">
    <li role="presentation"><a href="..">cvrminer</a></li>
    <li role="presentation"><a href="../branch/">Branch</a></li>
  </ul>
</div>
{% endblock %}

cvrminer/app/templates/exchange.html
{% extends "exchange_base.html" %}

{% block page_content %}

<h1>Exchange: {{ q }}</h1>


<h2>List of companies</h2>

<div class="embed-responsive embed-responsive-4by3">
  <iframe class="embed-responsive-item" src="https://query.wikidata.org/embed.html#SELECT%20%3Fcompany%20%3FcompanyLabel%20%3Fsymbol%20%0AWITH%20%7B%0A%20%20SELECT%20%3Fcompany%20%3Fsymbol%20WHERE%20%7B%0A%20%20%20%20%3Fcompany%20p%3AP414%20%3Fexchange_statement%20.%0A%20%20%20%20%3Fexchange_statement%20ps%3AP414%20wd%3A{{ q }}%20.%20%0A%20%20%20%20optional%20%7B%20%3Fexchange_statement%20pq%3AP249%20%3Fsymbol%20.%20%7D%0A%20%20%7D%0A%7D%20AS%20%25result%0AWHERE%20%7B%0A%20%20INCLUDE%20%25result%20.%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22da%2Cen%22%20.%20%7D%20%0A%7D%0A"></iframe>
</div>


<h2>Map of headquarters</h2>

<div class="embed-responsive embed-responsive-4by3">
  <iframe class="embed-responsive-item" src="https://query.wikidata.org/embed.html#%23defaultView%3AMap%0ASELECT%20%3Fgeo%20%3Fcompany%20%3FcompanyLabel%20%3Fsymbol%20%0AWITH%20%7B%0A%20%20SELECT%20%3Fcompany%20%3Fsymbol%20%3Fgeo%20WHERE%20%7B%0A%20%20%20%20%3Fcompany%20p%3AP414%20%3Fexchange_statement%20.%0A%20%20%20%20%3Fexchange_statement%20ps%3AP414%20wd%3A{{ q }}%20.%20%0A%20%20%20%20optional%20%7B%20%3Fexchange_statement%20pq%3AP249%20%3Fsymbol%20.%20%7D%0A%20%20%20%20%23%20%3Fcompany%20wdt%3AP159%2a%2Fwdt%3AP625%20%3Fgeo%20.%0A%20%20%20%20%3Fcompany%20p%3AP159%2Fpq%3AP625%20%3Fgeo%20.%0A%20%20%7D%0A%7D%20AS%20%25result%0AWHERE%20%7B%0A%20%20INCLUDE%20%25result%20.%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22da%2Cen%22%20.%20%7D%20%0A%7D%0A"></iframe>
</div>


{% endblock %}

cvrminer/app/templates/exchange_empty.html
{% extends "exchange_base.html" %}

{% block page_content %}


<h1>Exchange</h1>

<h2>Examples</h2>

<ul>
  <li><a href="Q1019983">Nasdaq Copenhagen</a></li>
  <li><a href="Q59551">Warsaw Stock Exchange</a></li>
</ul>


{% endblock %}

cvrminer/app/templates/index.html
{% extends "base.html" %}



{% block page_content %}

<h1>Danish companies</h1>

<ul>
  <li><a href="company/Q3949497">KMD A/S</a></li>
  <li><a href="cvr/29094195">CVR: 29094195 (Café Amalie)</a></li>
  <li><a href="cvr/27761291">CVR: 27761291 (William Demant Invest A/S)</a></li>
  <li><a href="branch/Q507443">Pharmaceutical industry</a></li>
  <li><a href="exchange/Q1019983">NASDAQ OMX Copenhagen</a></li>
</ul>

{% endblock %}

cvrminer/app/templates/person_empty.html
{% extends "base.html" %}

{% block page_content %}


<h1>Person</h1>

<h2>Examples</h2>

<ul>
    <li><a href="Q78336">Léo Apotheker</a></li>
    <li><a href="Q12323889">Lars Nørby Johansen</a></li>
    <li><a href="Q21002708">Kåre Schultz</a></li>
</ul>


{% endblock %}

cvrminer/app/templates/smiley.html
{% extends "base.html" %}

{% block content %}

<h1>Smiley</h1>

{{table | safe}}

{% endblock %}